### ISSUE TITLE
eventEmitter methods are not chainable

### ISSUE THREAD

**Issue by whitelynx** [rubenv/angular-tiny-eventemitter#1]
EventEmitter in node.js returns `this` from most of its methods (see [emitter.on docs](http://nodejs.org/docs/latest/api/events.html#events_emitter_on_event_listener)) so that they can be chained; for example:

``` javascript
var socket = sock.connect('foo')
    .on('connect', function() { ... })
    .on('message', function() { ... })
    .on('disconnect', function() { ... });
```

Could `return this;` be added to `on`, `once`, `off`, and `emit`?

**Comment by rubenv** [comment]
Sure, feel free to send a pull request, makes total sense.

**Comment by julianbei** [comment]
I have created a pull request for chaining #3
